### ISSUE TITLE
Parse string utils function

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#264]
## Description

- Write a function in the utils section (`src\utils.rs`) called `parse_string` that takes as an argument: a **string**, and an address (**FieldElement**). It should replace any occurrence in the specified string of: `{addr_hex}` by the given address (in **hex format**), and `{addr_dec)` by the given address (in **decimal format**).

→ There are utils functions to work with FieldElements, e.g. `to_hex` in `src\utils.rs`

**Comment by petersdt** [comment]
hi @Marchand-Nicolas kindly assign me this task i would like to make it my first contribution to the starknet quest api project

**Comment by vickiddev** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I will implement the parse_string utility function as follows:

Define the Function:
I'll create a new function parse_string in src/utils.rs that takes two parameters: a String and an address of type FieldElement.

Convert FieldElement to Hex and Decimal:
Using existing utility functions like to_hex in src/utils.rs, I'll convert the FieldElement address into both hex and decimal string formats.

Replace Placeholders:
I'll use Rust's str::replace method to replace all occurrences of {addr_hex} with the hex representation of the address and {addr_dec} with the decimal representation within the input string.


Return the Result:
The final string with the replaced values will be returned as the result of the parse_string function.
I'll ensure the function is efficient, well-tested, and handles edge cases such as when {addr_hex} or {addr_dec} doesn't exist in the input string.

ETA - 3 days

**Comment by juandiegocv27** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello! I'm Juan Diego Carballo, a software engineer and a proud member of the Dojo Coding community. I specialize in Rust, Cairo, and blockchain technologies. I've contributed to open-source Web3 projects like Starknet Quest, Dojo, and Op-Scan, focusing on enhancing user interfaces and experiences. My experience with Rust includes working on projects that require efficient handling of data and implementing complex functionalities.

At Mafisa, I led the development of an HR web application, which improved real-time data interaction and system reliability. This experience has honed my skills in delivering robust and user-centric solutions. Additionally, my participation in events like the Starknet Brussels HackerHouse and Starkhack has deepened my understanding of Starknet's ecosystem.

Given my background and active involvement in the Dojo Coding community, I'm confident that I can effectively contribute to the Starknet Quest API by implementing the required parse_string function with precision and adherence to best practices.

### How I plan on tackling this issue
To tackle this issue, I plan to:

Understand the Requirements:

Carefully read the issue description to fully grasp what's needed.
Review the existing src/utils.rs file to understand the current utility functions, especially those related to FieldElement.
Plan the Implementation:

Determine the best way to search and replace placeholders {addr_hex} and {addr_dec} in the input string.
Decide whether to use Rust's standard library functions or external crates for string manipulation, ensuring no additional dependencies are introduced without necessity.
Write the parse_string Function:

Implement the function to accept a String and a FieldElement as parameters.
Use existing utility functions like to_hex for converting the FieldElement to hex format.
Convert the FieldElement to decimal format using appropriate methods.
Replace Placeholders:

Utilize efficient string manipulation techniques to replace all instances of {addr_hex} and {addr_dec} with the corresponding address formats.
Ensure that the replacement is case-sensitive and accounts for multiple occurrences.
Testing:

Write unit tests to cover various scenarios, including strings with multiple placeholders, no placeholders, and edge cases.
Validate that the function behaves as expected and handles errors gracefully.
Documentation:

Add comments to the code explaining the logic and any important considerations.
Update any relevant documentation to include the new function.
Seek Feedback:

If I encounter any uncertainties, I'll consult the Rust documentation or reach out to the maintainers for clarification.
Open a draft PR to get early feedback and make necessary adjustments.
Finalize and Submit:

Ensure the code adheres to the project's style guidelines.
Run all tests to confirm that existing functionality remains unaffected.
Submit the pull request with a clear description of the changes and await further feedback.

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
GM, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, JavaScript and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
Hi @Marchand-Nicolas, I would approach this issue like this:
- Create a function parse_string in src/utils.rs to replace {addr_hex} and {addr_dec} with the given address in hex and decimal formats:
```
use crate::utils::FieldElement;
use crate::utils::to_hex;

pub fn parse_string(input: &str, address: FieldElement) -> String {
    let hex_address = to_hex(address);
    let dec_address = address.to_string();

    input
        .replace("{addr_hex}", &hex_address)
        .replace("{addr_dec}", &dec_address)
}
```

- Test this function to see it works as desired

### Tasks:
- [ ] Implement parse_string function

## ETA: 1 Day

**Comment by thesledge04** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience in Rust programming, particularly in developing utilities and functions for smart contracts. My background in implementing modular code can help streamline tasks like creating dynamic string parsing functions, enhancing the flexibility and functionality of the codebase.

### How I plan on tackling this issue
Create parse_string function.
Convert address to hex and decimal.
Replace placeholders in the string.
Return the modified string.
Implement tests for validation.

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Am an  Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.



My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45


My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


### How I plan on tackling this issue
I'll implement using the following 

 -  new function parse_string in src/utils.rs, which will accept two parameters  a String and an address of type FieldElement.

- Convert FieldElement to Hex and Decimal: Using utility functions like to_hex from src/utils.rs, I'll convert the FieldElement address into both hexadecimal and decimal string formats.

- Replace Placeholders: By leveraging Rust's str::replace method, I'll substitute all instances of {addr_hex} with the hexadecimal representation and {addr_dec} with the decimal representation within the provided string.

ETH: 18hrs

**Comment by ahmadou-ai** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hi ! I'm a fullstack developer with 4 years of experience, living in france. I recently developed a strong interest in web3 and especially in starknet ecosystem. I would love to leverage my knowledge with contributions to your exciting project !

### How I plan on tackling this issue
To implement the parse_string function in utils.rs, I would create a utility that takes a string and a FieldElement address as inputs, replacing placeholders {addr_hex} and {addr_dec} in the string with the address's hexadecimal and decimal representations, respectively. Using Rust's string manipulation methods, I would replace these placeholders and ensure proper error handling and input validation. The function would be thoroughly tested to handle various input scenarios, ensuring robust performance and correctness.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding.I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. Create parse_string function that takes a string (input) and a FieldElement address as parameters.
2. Convert address to hexadecimal.
3. Convert hexadecimal address to decimal
4. Replaces addr_hex in the input string with the hexadecimal string and addr_dec with the decimal string
5. Finally return string with replaced placeholders

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, and C# with .NET Entity Framework, among others. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration. I have already made a contribution to Starknet Quest, and I am eager to take on more opportunities

### How I plan on tackling this issue
To implement parse_string in src/utils.rs, I would define the function with a string and a FieldElement as parameters. I would use functions like to_hex to convert the address to both hexadecimal and decimal formats. Then, I would apply string manipulation methods to replace occurrences of {addr_hex} and {addr_dec} with their respective representations. Finally, I would return the modified string.

**Comment by jsanchez556** [comment]
@Marchand-Nicolas Thank you for the incredible opportunity to collaborate on this amazing project!

**Comment by Marchand-Nicolas** [comment]
Done here: https://github.com/lfglabs-dev/api.starknet.quest/pull/271
