### ISSUE TITLE
Admin routes for contract tasks

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#267]
## Description

Implement the necessary admin routes to create and edit a new `contract` task type.

## PROPOSED TODO

- [ ] Create a `contract` folder in `src\endpoints\admin` containing a `create_contract` and an `update_contract` route (such as in `src\endpoints\admin\balance`), which are dedicated to creating & updating contract tasks.
- [ ]  It should take a `calls` (Array of `Call`) field as an argument in the body (among the other default fields such as the task name), and store it in the task document in the db (as we are doing for other task types, such as in `src\endpoints\admin\balance`.).
Each `Call` is an object with the following fields `contract` (string), `call_data` (string array), `entry_point` (string), `regex` (string).
- [ ] Add the `calls` optional field to the `QuestTaskDocument` type in `src\models.rs` if it is not already present. If it doesn't already exist, I suggest you to create a `Call` type that you can then use to type the `Calls` field.
- [ ] The new document should look something like that:
```rs
    let new_document = QuestTaskDocument {
        name: body.name.clone(),
        desc: body.desc.clone(),
        verify_redirect: None,
        href: body.href.clone(),
        total_amount: None,
        quest_id: body.quest_id,
        id: next_id,
        cta: body.cta.clone(),
        verify_endpoint: "quests/verify_contract".to_string(),
        verify_endpoint_type: "default".to_string(),
        task_type: Some("contract".to_string()),
        discord_guild_id: None,
        quiz_name: None,
        contracts: None,
        calls: Some(body.calls),
    };
```

**Comment by Luluameh** [comment]
Hello @Marchand-Nicolas 
I can handle this 
I will love to fix this issue

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.

My recent Proof of work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


My recent proof of  work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



### How I plan on tackling this issue
I have read the description

This issue, am going to create two endpoints
- Create contract and update contract
- The body of create contract will take body that has CALL data object which has the following field, contact name, call_data, entry point and regex and also make the call field an option field inside the QuestTaskDocument, 

ETA : 16HRS

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, and C# with .NET Entity Framework, among others. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration. I have already made a contribution to Starknet Quest, and I am eager to take on more opportunities

### How I plan on tackling this issue
To implement the admin routes for creating and editing contract tasks, I first create the src/endpoints/admin folder and within it, the create_contract.js and update_contract.js files. In create_contract.js, I define a POST route that receives an object with the calls field and uses it to create a new QuestTaskDocument, ensuring the calls field is included as a vector of Call.

The Call type is defined in src/models.rs, with the fields contract, call_data, entry_point, and regex. Then, in update_contract.js, I set up a PUT route that updates an existing document, allowing the modification of fields, including calls.

Finally, I perform tests to verify that the create and update operations work correctly and that the documents are stored properly in the database.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach this issue in the following manner: 


1. Create a new folder `contract` in `src\endpoints\admin`. 

2. Implement `create_contract.rs`: 

   a. Define a request body struct with fields for task details and `calls`. 

   b. Validate input data. 

   c. Generate a new task ID. 

   d. Create a new `QuestTaskDocument` with "contract" task type and provided data. 

   e. Insert the document into the database. 

   f. Return a success response with the created task details. 

3. Implement `update_contract.rs`: 

   a. Define a request body struct similar to create, but with an `id` field. 

   b. Retrieve the existing task document by ID. 

   c. Update the document with new data, preserving unchanged fields. 

   d. Save the updated document to the database. 

   e. Return a success response with the updated task details. 

4. Add error handling for database operations and input validation. 

5. Update the admin API router to include these new routes.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I will implement the admin routes for contract tasks by following these steps:

Create Contract Folder and Routes:
I will create a contract folder under src/endpoints/admin.
Inside this folder, I'll add create_contract.rs and update_contract.rs routes, similar to how it's structured for balance in src/endpoints/admin/balance.

Handle Calls Field in Routes:
The create_contract and update_contract routes will accept a calls field (an array of Call objects) in the request body, along with other fields like task name.
Each Call object will include contract (string), call_data (string array), entry_point (string), and regex (string).

Update QuestTaskDocument Type:
I'll add the calls field to the QuestTaskDocument type in src/models.rs if it doesn't already exist.
If the Call type isn't defined yet, I'll create it to ensure a clear and structured data model.

Store the New Document:
I will construct the new document as specified
I'll ensure that the document structure matches the existing patterns for consistency.
Testing and Validation:

I'll thoroughly test both create_contract and update_contract routes to verify they handle the calls data correctly and store it in the database without issues.
Let me know if there are any other specifics you'd like me to include!

ETA - 3 days

**Comment by mubarak23** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Experience Cairo smart contract developer with experience working on projects such as Just Art Peace, Dojo, Kart, TBA, and Shinigami. Before transitioning to Cairo development, I was a backend developer specializing in Rust.

My recent work with cairo starknet
- https://github.com/keep-starknet-strange/raito/pull/128
- https://github.com/keep-starknet-strange/raito/pull/143
- https://github.com/horuslabsio/TBA/pull/45
- https://github.com/horuslabsio/karst-core/pull/60
- https://github.com/keep-starknet-strange/art-peace/pull/121
- https://github.com/keep-starknet-strange/zkramp/pull/33
- https://github.com/keep-starknet-strange/art-peace/pull/32
- https://github.com/horuslabsio/TBA/pull/53



My recent work with rust
- https://github.com/mubarak23/axum-user-auth
- https://github.com/antoyo/rustc_codegen_gcc/pull/1
- https://github.com/antoyo/rustc_codegen_gcc/pull/5
- https://github.com/fedimint/fedimint/pull/5994
- https://github.com/mubarak23/soroban-bank


### How I plan on tackling this issue
I have read the description

This issue, am going to create two endpoints

  -    CREATE CONTRACT TASK 
     - The body of create contract will take body that has CALL data object which has the following field, contact name, call_data, entry point and regex and also make the call field an option field inside the QuestTaskDocument,
     
 1. collect the request body
 2. validate the request body
 3.  save in the db
 4. return error if save fail
 5. return successful response after saving the data 

- EDIT CONTRACT TASK 
    1. collect the id of the contract we are going to edit
    2. find the contract task
    3. if it's does not exist, return error
    4. if its's exist update the record
    5. if update is successful, return the correct response
    6. if update fail, return the right error response. 

ETA : 16HRS

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
With over 3 years of experience in blockchain and backend development, I have worked across multiple blockchain ecosystems. My expertise spans the entire development lifecycle—from project conceptualization and smart contract design to managing on-chain interactions, seamless protocol integration, and implementing strong security practices.

This enables me to handle both on-chain and off-chain infrastructure, ensuring the development of reliable, scalable blockchain applications.

### How I plan on tackling this issue
Study the codebase to ensure design consitency, then implement the assigned tasks.

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
i'm a solidity and cairo smart contract  developer with over 2 years experience and belive i have the skill set for the task

**Comment by GideonBature** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Software Engineer with experience in building backend using Rust, I am quite good with Rust and other programming languages including JavaScript, TypeScript, Cairo and NodeJS. I am also an open source contributor and made my first contribution in the ODHack #7.0 which was successfully merged.

### How I plan on tackling this issue
First is to look at how the existing routes are been structured, that would give me an idea on how to structure my code, next I will look closely at what is to be implemented by following the PROPOSED TODO, as I build I will keep testing to make sure it's working the way it is supposed to.
