### ISSUE TITLE
Add base APRs for Nimbora

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#281]
There is the following problem in `src/endpoints/discover/defi/get_alt_protocol_stats.rs`: we only count DeFi Spring APRs. This route should return the APRs of different strategies, but it is currently only using the APRs provided by the DeFi Spring for these strategies. The aim of this issue is to add an API call to Nimbora at the begining of the file, so that the APR of every strategy returned by the DeFi Spring API is replaced by the one from the Nimbora API (which counts the base APR + the DeFi Spring one).

Example to illustrate:
When  calling`https://api.starknet.quest/discover/defi/get_alt_protocol_stats` (which is the current state of the API), we get:
<img width="650" alt="image" src="https://github.com/user-attachments/assets/94ac2e85-99c2-4d02-9234-d4993925bd1b">

And when calling the Nimbora API `https://stats.nimbora.io/yield-dex/strategies`:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/8f9bbef7-0b09-4b97-8af1-d8d7fba30abf"> 
We get, (this screenshot only contains this example strategy, but all other strategies are returned by the API), for instance,
``` "aprBreakdown": {
      "base": "0.7026797371850104",
      "boost": "0",
      "incentives": "13.09410701089488"
    },
    "apr": "13.7967867480798904",
```
The problem is that our API only count the `incentives`(returned by the DeFi Spring API), and not the base. That's why you'll need to use both API's, to get the accurate computer APR.

You'll need to set the following field in you `config.toml` in order to test:
```toml
alt_protocols_api_endpoint = "https://kx58j6x5me.execute-api.us-east-1.amazonaws.com/starknet/fetchFile?file=prod-api/phase4/phase4_strk_grant.json"
```

Suggested implementation:
- At the begining of the route, call the Nimbora's API to fetch strategies APRs.
- At the end of the route, just before returning the response, map every strategy, and find (if available => because in the future we could have other protocols than Nimbora, so the Nibmora's API wouldn't have the data for them), in the stored response from Nimbora, the related strategy. Then collect and update the APR.
- If there is any issue when calling Nimbora's API, just ignore its response and proceed without this data (meaning you only use the one from DeFi spring as we are currently doing)

**Comment by ShantelPeters** [comment]
Hi @Marchand-Nicolas please can I be assigned to this issue , I will love to work on it

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I would like to be assigned this issue. I'll prioritize it and begin working on it immediately

**Comment by mimisavage** [comment]
@Marchand-Nicolas can I be assigned this task? I'll deliver as soon as possible

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, and C# with .NET Entity Framework, among others. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration. I have already made a contribution to Starknet Quest, and I am eager to take on more opportunities

### How I plan on tackling this issue
I would start by adding a Nimbora API call to the beginning of the path in get_alt_protocol_stats.rs. I would use a library like reqwest to make the HTTP request, deserializing the response into a structure containing the APR values ​​for each strategy, including base and incentives. If the call fails, I handle the error by returning only the current DeFi Spring data.

After getting the data from Nimbora, the DeFi Spring APRs, which only include incentives, are processed as usual. Then, for each strategy returned by DeFi Spring, I would look for the matching strategy in the Nimbora response. If a match is found, I replace the DeFi Spring APR value with the Nimbora APR value (which includes both base and incentives).

If a matching strategy is not found in Nimbora or if an error occurs during the call to its API, the system continues to run by returning the data from DeFi Spring. This ensures that the integration with the Nimbora API is solid and does not interrupt the current flow of the system.

For testing, I also add the alt_protocols_api_endpoint field to the config.toml configuration file, allowing you to easily change the endpoint.

**Comment by GideonBature** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a Software Engineer with working knowledge of Rust, also proficient in JavaScript and TypeScript. I have built projects personally on Rust, also JavaScript and TypeScript. Also, I have contributed to the Stark Quest project for the first time during the just concluded ODhack. I have worked with APIs before and even built some in Actix Web, hence I believe that my experiencial knowledge will definitely help me in solving this challenge. 

### How I plan on tackling this issue
First of all I will go through the Readme once again to see if there are any changes to setting up my environment for testing, as I have the repository set up on my local machine already so that I will be able to test my work.

Next, I will go through the file having this problem to see what is currently there and From the description of the problem, there is a very clear suggestion which is to first call the Nimbora's API to fetch strategies, afterwards using a map to check if the strategy is available or not, as this will make the code scalable, since there is the possibility of having more protocols other than Nimbora's in the future.

Finally, if there are issues with calling Nimbora's API, it's to leave it so as for it to default to using the Data from DeFi spring. Afterwards I test to make sure it's working.

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I’m a Software Developer with +3 years of experience, also a member of the Dojo Coding 

### How I plan on tackling this issue


I’ll first review the existing project architecture and infrastructure requirements to ensure I have a complete understanding of what is needed for api.starknet.quest

I’d add a call to Nimbora's API at the start of the route to fetch the APRs for different strategies. This will allow us to gather the base APR and any other additional data Nimbora provides.

Next, after getting the data from both the DeFi Spring API and Nimbora, I would map each strategy from DeFi Spring to the corresponding strategy from Nimbora. If a match is found, I’d replace the APR from DeFi Spring with the one from Nimbora, which includes both the base and incentives APR.

If there's an issue calling Nimbora's API, I would ignore it and proceed with only the DeFi Spring data, ensuring the system continues working as it currently does.

If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by Benjtalkshow** [comment]
GM @Marchand-Nicolas 
I would be glad to work on this issue. Thanks
