### ISSUE TITLE
Add Vesu for DeFiSpring rewards

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#302]
Add Vesu in `src\endpoints\defi\rewards.rs`, as we already did with Zklend, Nostra, Nimbora, and Ekubo. Each protocol has its own way to manage DeFiSpring rewards, so you'll have to check their docs: https://staging.api.vesu.xyz/docs/#/default/get_strk_rewards
Here is their contract: `0x0387f3eb1d98632fbe3440a9f1385aec9d87b6172491d3dd81f1c35a7c61048f`

If you need more details: https://github.com/lfglabs-dev/api.starknet.quest/issues/279

**Comment by ShantelPeters** [comment]
Hi @Marchand-Nicolas please can I be assigned to this issue?

**Comment by ooochoche** [comment]
@Marchand-Nicolas I can work on the issue

**Comment by PoulavBhowmick03** [comment]
Would love to work on this!

**Comment by PoulavBhowmick03** [comment]
I’d like to help with this.

I'm Poulav Bhowmick, a Starknet Wolf.  I´m active member of Starknet, Ethereum, Stellar ecosystem. I have also contributed to this project so I have a pretty good idea of how things work.

### Approach

I will integrate Vesu into src\endpoints\defi\rewards.rs by creating a function that interacts with Vesu’s API. First, I will study the API documentation to understand how Vesu structures its STRK reward responses, using the contract address provided, I will implement calls to retrieve STRK rewards and parse the data to meet the DeFiSpring reward structure.

## ETA - 1 day

**Comment by vitaliypopel** [comment]
May I be assigned to this? I'll do my best

**Comment by binayak9932** [comment]
I am Binayak Mondal, I am a Rust and Cairo contributor

I would like to solve this by going through the docs as is given. Then i will check out the other implementations of other networks. Then I will add Vesu to src\endpoints\defi\rewards.rs

ETA - 1 day

**Comment by 0xBinayak** [comment]
I am Binayak Mondal, I am a  new Rust and Cairo contributor

### I would like to solve this by going through the docs as is given. Then i will check out the other implementations of other networks. Then I will add Vesu to src\endpoints\defi\rewards.rs

ETA - 1 day

**Comment by Benjtalkshow** [comment]
@Marchand-Nicolas, 
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

To add Vesu for `DeFiSpring rewards`, I will integrate it within the `src/endpoints/defi/rewards.rs` file, similar to the existing implementations for Zklend, Nostra, Nimbora, and Ekubo. 

I will study the Vesu's documentation thoroughly and also check how the api details are returned. Based on the API details, I’ll configure the request logic in the rewards endpoint, ensuring it accurately retrieves and processes reward data from Vesu’s endpoint. The response will then be formatted in line with the DeFiSpring rewards structure. I'll also incorporate the associated Vesu contract into the contract calls as needed.

Finally, I will test the integration to confirm it meets performance expectations, including compatibility and error handling.
My ETA is 48hrs. Thanks

**Comment by ryzen-xp** [comment]
Is it okay if I tackle this?
Please /assign  me

**Comment by martinvibes** [comment]
hey @fricoben Can I contribute to this one?

**Comment by pheobeayo** [comment]
May I handle this issue?

**Comment by Ugo-X** [comment]
I'd love to work on this!
please can i be assigned to this?

**Comment by casweeney** [comment]
## About me:
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. Using Rust, I built a CLI tool that is currently being used with over one thousand downloads on crate.io : https://crates.io/crates/resolver-cli

I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

## Solving this issue:
I have looked at the code on `src\endpoints\defi\rewards.rs`and I can see the implementation for Zklend, Nostra, Nimbora, and Ekubo. I have also taken a look at Vesu API doc on Swagger.

- I will create a function `fn fetch_vesu_rewards()`
- Following the already existing implementations for other existing protocols, I will implement the `fetch_vesu_rewards()` function to fetch rewards using the Vesu API.

### ETA: 48 hours max
With my technical experience, I will deliver this task within 48 hours or less.

**Comment by mimisavage** [comment]
Could I grab this task?

**Comment by MrRoudyk** [comment]
Can I take this issue?
About me:
Software Engineer with 10 years of experience. For the past 5 years, I’ve specialized in HR Tech solutions. I’m passionate about exploring new technologies and currently looking to deepen my expertise in blockchain, smart contracts, and decentralized applications. I have also contributed to open source development at OnlyDust ([My OnlyDust Profile](https://app.onlydust.com/u/MrRoudyk)).

How I plan on tackling this issue:
First, I will review the existing reward integrations in `rewards.rs`. Then, I will study Vesu's documentation to understand their DeFiSpring rewards management. Using this information, I will implement the necessary code to add Vesu to `src/endpoints/defi/rewards.rs`

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://www.onlydust.com/).

## My background and how it can be leveraged

Hi, I'm Alvaro Lazarus a new member of Dojo Coding, im relativley new to blockchain but I have worked with rust before which makes me confident that I can complete this issue.

## How I plan on tackling this issue

1. Review the code for similar protocols.
2. Examine Vesu API documentation.
3. Implement fn fetch_vesu_rewards() following existing patterns.
4. Test for functionality and consistency.

Please consider 

ETA: 48 hrs

**Comment by Akshola00** [comment]
Can I attempt this issue?

**Comment by martinvibes** [comment]
Hello @Marchand-Nicolas I would love to handle this issue

**Comment by tasneemtoolba** [comment]
Can I contribute to this one? new to the field, a new H.E.R DAO member

**Comment by SoarinSkySagar** [comment]
## Background
I am a full stack engineer and smart contract developer with 3 years of experience. I am proficient in my Rust skills. 
## Approach
I can see the how the rest of the protocols have been implemented, and in the given link I have also seen how Vesu retrieved the rewards using the /strk-rewards endpoint. I will implement this feature and make sure it works, and it won't take much time because it is a very straightforward task.
## ETA: 1 Day

**Comment by GideonBature** [comment]
May I try my hand at this please?

**Comment by aniruddhaaps** [comment]
I'm a rust dev, a new-comer here. Want to contribute to the problem and provide with a solution.

**Comment by baitcode** [comment]
I'd love to attempt the problem.

Experience: https://www.linkedin.com/in/batiyiv/
Plan:
- Study other integrations
- Implement the API, add unit test
- Check integration testing cases, update accordingly
- Check if doc is affected

Not sure, if I'll be quick with this one. Seems like might take 4-5 days.

**Comment by BrunoAmbricca** [comment]
Hello, Im a software engineer with 4+ years of experience and I would like to contribute to this project

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?

**Comment by vijay-kesanakurthi** [comment]
I’d like to help with this.

**Comment by mimisavage** [comment]
I want to take on this issue, can I be assigned?
