### ISSUE TITLE
Fix boost fields types

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#311]
`num_of_winners` and `token_decimals` are currently i64 in most of the code, but they should be i32.
Update `src\endpoints\admin\quest_boost\create_boost.rs`, `src\endpoints\admin\quest_boost\update_boost.rs` and `src\models.rs` to replace they types by i32.

**Comment by PoulavBhowmick03** [comment]
May I take care of this?

I am Poulav Bhowmick, a Starknet Wolf, contributor to the Starknet ecosystem and Superteam grants recipient.

To resolve this issue, I will update the type declarations for `num_of_winners` and `token_decimals` from `i64` to `i32` across the codebase. I will modify these fields in `src/endpoints/admin/quest_boost/create_boost.rs`, `src/endpoints/admin/quest_boost/update_boost.rs`, and `src/models.rs`. After changing the types, I will review related logic to ensure that all operations and calculations are compatible with `i32`.

ETA - 8 hours

**Comment by hannahredler** [comment]
Hey! Im Hannah, a dev recently joining the starknet ecosystem. Would love to take this task if possible!

**Comment by Benjtalkshow** [comment]
Hello @Marchand-Nicolas 
Can i be assigned to this task? i will make PR in 5hrs. Looking forward to contribute to this amazing project.

**Comment by ooochoche** [comment]
@Marchand-Nicolas I’d be happy to tackle this issue! I’ve contributed to this repo before, but not yet for this odhack, so I’d love to get involved with this task.

**Comment by hannahredler** [comment]
Great, thanks! Working on this now 🚀
