### ISSUE TITLE
Fix compilation warnings

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#320]
## Description 📹

**Fix the warnings that appears when using `cargo build` (e.g. unused variables)**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] run `cargo build` and check every warnings
- [ ] For each warning, fix it if you think it's worth it

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by 847850277** [comment]
Can you assign this issue to me? I can complete it。

**Comment by GideonBature** [comment]
Greetings @Marchand-Nicolas, can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again to Starknet Quest by solving this issue. I have experience working with Rust and some of it's framework (Axum and Actix-web). For this project, I will send my first PR within 48 hrs. I will carefully follow the warning generated by the rustc after running ***cargo build***, for unused variables, I will either remove them or append them with an underscore most especially if I find out that they might likely be used later in the code.

Thank you.

**Comment by 0xdevcollins** [comment]
May I take care of this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by Akshola00** [comment]
May I be assigned to this?

**Comment by PedroCo3lho** [comment]
Can I contribute to this one? I have a good understanding of Cairo by completing the Starklings, studying the Cairo Book and I'm also a Cairo Basecamp Graduate.

**Comment by Michaelkingsdev** [comment]
Let me try this one!

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by saimeunt** [comment]
Hey I'm a returning contributor to the API, would love to handle this one and fix the compilation warnings.

**Comment by josephchimebuka** [comment]
Could I take a shot at this?

**Comment by aspiringLilCoder** [comment]
Could I try solving this?

**Comment by Emmanex01** [comment]
I'd like to take this issue.

**Comment by pheobeayo** [comment]
I'd love to give this a go.

**Comment by blessingbytes** [comment]
I am a frontend and blockchain developer specializing in creating intuitive user interfaces. I have experience with modern frameworks like React and smart contract development on platforms like Ethereum and Starknet. Pls i would love to tackle this issue. plss

**Comment by DioChuks** [comment]
Can I start working on this?

**Comment by hossamanany** [comment]
May I handle this issue?

**Comment by DioChuks** [comment]
Alright, I'll get started!
