### ISSUE TITLE
Reinforce the WatchTower implementation

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#321]
## Description 📹

**Replace println & eprintln by WatchTower (our own logger) as done in src/endpoints/quest_boost/get_pending_claims.rs**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Use the global search tool provided by your IDE to find all occurences of println and replace them, if possible, by our logger

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by anonfedora** [comment]
I'm Eleazar a fullstack Blockchain developer. Can refactor println and eprintln with custom watchtower logger.
ETA 48 hours.

**Comment by GideonBature** [comment]
Greetings @Marchand-Nicolas, can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again to Starknet Quest by solving this issue. I have experience working with Rust and some of it's framework (Axum and Actix-web). For this project, I will send my first PR within 48 hrs.

Thank you.

**Comment by joeperpetua** [comment]
Hi guys, I have worked with the front client previously, I would love to start getting more involved with the backend service too. I have mostly Cairo experience, so I think this is a good issue to gain some experience in rust code bases

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

I'm a member of **Dojo Coding** and have previously contributed before to this project and projects like:

- `kakarot-rpc`
- `ef-tests`
- `Madara`
- `Raito`
- `Starknet-Phone`

I'd like to work on this issue.

Check my OnlyDust profile for my contributions: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Review the WatchTower Implementation** in `api.starknet.quest` to understand its setup and functionality.

2. **Assess the Current Repository** to determine how to integrate WatchTower seamlessly.

3. **Implement WatchTower**:
   - Adapt the implementation to fit the current project's structure.
   - Add and document any necessary dependencies.

4. **Test the Implementation**:
   - Ensure existing functionalities remain unaffected.
   - Write tests for the new WatchTower functionality.

5. **Document Changes**:
   - Update code comments and documentation to explain the new setup.

6. **Commit Changes** with a clear message

7. **Open a Pull Request** and await feedback.

---

**Comment by Supa-mega** [comment]
Can I jump on this task?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by JoE11-y** [comment]
I’d like to resolve this.

**Comment by Michaelkingsdev** [comment]
May I be assigned to this?

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue?

**Comment by Michaelkingsdev** [comment]
@Marchand-Nicolas 
I will start working on this. Thanks.

**Comment by Michaelkingsdev** [comment]
Hello @Marchand-Nicolas 
I am still working on this.  I just want to let you know.
