### ISSUE TITLE
Add tests for the to_hex and the to_hex_trimmed

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#322]
## Description 📹

**Add tests for the "to_hex" and the "to_hex_trimmed" functions (from the utils folder) like we’ve done in `tests/endpoints.rs`**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Create a "utils.rs" file in the `tests` folder
- [ ] Fill it with the two requested tests
- [ ] You can reuse the way we've done tests in `tests/endpoints.rs*`

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by GideonBature** [comment]
Greetings @Marchand-Nicolas, can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again to Starknet by solving this issue. I have experience writing Rust code and tests using some of it's framework (Axum and Actix-web). For this project, I will send my first PR within 72 hrs.

Thank you.

**Comment by joeperpetua** [comment]
Hi guys, I have worked with the front client previously, I would love to start getting more involved with the backend service too. I have mostly Cairo experience, so I think this is a good issue to gain some experience in rust code bases

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

I'm a member of **Dojo Coding** and have previously contributed to this project and projects such as:

- `kakarot-rpc`
- `ef-tests`
- `Madara`
- `Raito`
- `Starknet-Phone`

I would like to work on this issue.

You can check my OnlyDust profile to see my contributions to various projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase**, focusing on the `utils` folder and the existing tests in `tests/endpoints.rs` to understand the current implementation and testing patterns.
2. **Review the `to_hex` and `to_hex_trimmed` functions** to fully grasp their functionality and how they are used within the project.
3. **Create a `utils.rs` file** inside the `tests` folder to house the new tests for these functions.
4. **Write comprehensive tests** for both `to_hex` and `to_hex_trimmed`, covering various input scenarios and edge cases, following the testing patterns from `tests/endpoints.rs` for consistency.
5. **Run all tests** to ensure that the new tests pass and do not affect existing functionality.
6. **Commit the changes** with a clear and descriptive message
7. **Push the branch** to my forked repository and **open a Pull Request** for review.
8. If I encounter any issues, I will **ask questions promptly** in the Telegram group to ensure smooth progress.
9. **Address any feedback** received during the PR review to refine the changes until the PR is ready to be merged.

---

**Comment by Supa-mega** [comment]
I’d like to work on this.

**Comment by No-bodyq** [comment]
Can I handle this task?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by No-bodyq** [comment]
Can I handle this task?
It will be my first time contributing on this project 
Please assign

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by Akshola00** [comment]
Would love to tackle this!

**Comment by Michaelkingsdev** [comment]
May I take this issue on?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Amarjeet325** [comment]
May I try my hand at this?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by saimeunt** [comment]
Hey I'm a returning contributor to the API, I'd like to handle this one please!

**Comment by Emmanex01** [comment]
Is it okay if I tackle this?

**Comment by guha-rahul** [comment]
Can I take it up? It would be fun experience writing production level tests . Thank you

**Comment by aspiringLilCoder** [comment]
I'd love to give this a go.

**Comment by 0xdevcollins** [comment]
Could I take on this issue?

**Comment by blessingbytes** [comment]
pls , i would love to tackle this issue

**Comment by aurlic** [comment]
Hey, I would love to be able to work on this issue as my first OD issue. I am currently learning both Rust and Cairo, and would love to put my new skills to the test. Thank you in advance !
