### ISSUE TITLE
Delete some routes

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#323]
## Description 📹

**Delete the following routes: `src/endpoints/quests/ekubo/discord_fw_callback.rs`, `src/endpoints/quests/focustree/engagement/discord_fw_callback.rs`, `src/endpoints/quests/nostra/liquidity_quest/discord_fw_callback.rs`** as they are now unused

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Delete these files: src/endpoints/quests/ekubo/discord_fw_callback.rs, src/endpoints/quests/focustree/engagement/discord_fw_callback.rs, src/endpoints/quests/nostra/liquidity_quest/discord_fw_callback.rs

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Benjtalkshow** [comment]
Hey @Marchand-Nicolas
Please can i work on this ? My ETA is 48hrs. Thanks

**Comment by anonfedora** [comment]
Hey @Marchand-Nicolas I'm a fullstack Blockchain developer (Backend heavy), can tackle this.
ETA 4 hours...

**Comment by GideonBature** [comment]
Greetings @Marchand-Nicolas, can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again to Starknet by solving this issue. I have experience with Rust and some of it's framework (Axum and Actix-web). For this project, I will send my first PR within 24 hrs.

Thank you.

**Comment by omsant02** [comment]
I’d like to resolve this.

**Comment by Supa-mega** [comment]
can i please be assigned this task

**Comment by Akshola00** [comment]
Is this issue still available?

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by SudiptaPaul-31** [comment]
Please assign me this issue

My approach to tackle this issue:

Will start by locating the routes
Will delete the routes present and check if there exists any error or not
And will run it properly and test it before making a pr

**Comment by pheobeayo** [comment]
I’d like to work on this. 

I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

How I plan to tackle this issue.
- I will delete the routes that need to be deleted
- Test the code
- Check for any breakage in the codebase.
- Create a PR.
- Request for a Review.

**Comment by jancris100** [comment]
Could I take over this issue?Would love to tackle this! I'm from dojo coding I have 2 years of experience as full stack developer and also Im actually work in spa app with angular and asp.net so I'm good on backend Developer

**Comment by Aditya-040** [comment]
May I take care of this?

**Comment by 0xDeon** [comment]
Could I try solving this?
ETA: 24 hrs

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly.  To solve this issue I’d delete the unused files, run tests to ensure nothing breaks, and commit the changes with a clear message. Then, I’d push the branch and open a pull request for review.I would really love to be assigned this issue and work on this project.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by OWK50GA** [comment]
Can I be assigned this task?
ETA - 24 hours

**Comment by Marchand-Nicolas** [comment]
Done here https://github.com/lfglabs-dev/api.starknet.quest/pull/333
