### ISSUE TITLE
Create New Admin Route `get_boost_winners`

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#324]
## Description 📹

Implement a new admin route `get_boost_winners` that retrieves the list of winners for a specific boost. This route will allow admin users to fetch the winners based on the `boost_id` provided. It should be secured using the existing authentication middleware to ensure only authorized admin users can access this information.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:

   - **Create the Route**: add a new handler in `src/endpoints/admin/quest_boost`: `get_boost_winners.rs`

   - **Define Request Parameters**:

     ```rust
     pub_struct!(Deserialize; GetBoostWinnersParams {
         boost_id: i64,
     });
     ```

   - **Implement the Handler Logic, which should look something like that**:

     ```rust
     #[route(get, "/admin/boosts/get_boost_winners", auth_middleware)]
     pub async fn get_boost_winners_handler(
         State(state): State<Arc<AppState>>,
         Extension(_sub): Extension<String>, // Assuming admin authentication is handled
         Query(params): Query<GetBoostWinnersParams>,
     ) -> impl IntoResponse {
         let collection = state.db.collection::<BoostDocument>("boosts");

         let filter = doc! { "id": params.boost_id };

         match collection.find_one(filter, None).await {
             Ok(Some(boost_doc)) => (
                 StatusCode::OK,
                 Json(json!({ "winners": boost_doc.winner })).into_response(),
             ),
             Ok(None) => get_error(format!("Boost with id {} not found", params.boost_id)),
             Err(e) => get_error(format!("Error fetching boost winners: {}", e)),
         }
     }
     ```

3. **Run Tests and Commit Changes**:

   - **Testing**:
     - Verify the new route works as expected by testing with valid and invalid `boost_id` values.
     - Ensure that unauthorized access is correctly blocked by the `auth_middleware`.

   - **Commit Changes**:

     ```bash
     git commit -m "Fix: Implement get_boost_winners admin route"
     ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ **WARNING**: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Benjtalkshow** [comment]
Hey @Marchand-Nicolas 
Please can i work on this ? My ETA is 48hrs. Thanks

**Comment by anonfedora** [comment]
I'm Eleazar a fullstack Blockchain developer (backend heavy).
Can handle this, ETA 72 Hours.

**Comment by GideonBature** [comment]
Greetings @Marchand-Nicolas, can you please assign this issue to me?

I am a software engineer and have participated and contributed to previous ODHacks. I would love to contribute once again to Starknet by solving this issue. I have experience with Rust and some of it's framework (Axum and Actix-web) I will be able to send my first PR within 48 hrs.

Thank you.

**Comment by Benjtalkshow** [comment]
May I take care of this?

**Comment by omsant02** [comment]
Would love to tackle this!

**Comment by hannahredler** [comment]
Hey! I am a full stack dev, I have worked on a task in this repo before it was great to work with you guys! I would appreciate the chance to work on this task.

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by Supa-mega** [comment]
May I try my hand at this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many stark net project and more  .   please /assign  this issue .
Thank You

**Comment by No-bodyq** [comment]
Is this issue still available?

**Comment by Ugo-X** [comment]
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 92 significant contributions across 19 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  


I have previous experience implementing this and would love to be assigned to this issue.

**Comment by Michaelkingsdev** [comment]
I'd love to give this a go.
