### ISSUE TITLE
Edit get_quest_users to return hex

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#342]
## Description 📹

**Update `src/endpoints/admin/quest_boost/get_quest_users.rs` to return addresses in hex format, similar to `src/endpoints/admin/quest/get_quest_participants.rs`. Ensure that all returned addresses are converted to hex using the `to_hex` utility function.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
Update the following sections in `get_quest_users.rs`:
   - Modify the portion where the user addresses are collected and ensure the conversion of all addresses to hex using the `to_hex` function.
   - Replace any existing logic that directly adds or uses addresses in decimal format.

   ### Code snippet update suggestion:
   Replace:
   ```rust
   let users_list: Vec<String> = user_set.into_iter().collect();
   ```
   With:
   ```rust
   let users_list: Vec<String> = user_set
       .into_iter()
       .filter_map(|addr| FieldElement::from_dec_str(&addr).ok().map(to_hex))
       .collect();
   ```

   - Test to ensure all logic aligns with the behavior in `get_quest_participants.rs`.

3. **Run Tests and Commit Changes**:  
   - Test locally to ensure the modified function correctly returns hex-formatted addresses.
   - Run existing tests and write any additional tests to validate the changes.

```bash
   git commit -m "Fix: Update get_quest_users to return addresses in hex format"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Supa-mega** [comment]
Let me try this one!

**Comment by Emmykeyz101** [comment]
Mind if I take this issue?

**Comment by jaykayudo** [comment]
Can i be assigned this when ODHack starts?
I am new here and i will love to contribute to this project.
I will follow the guildeline and ensure that i get it done within the specified timeframe.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by 3th-Enjay** [comment]
Can I tackle this one?

**Comment by Nanle100** [comment]
Is it okay if I tackle this?

**Comment by mimisavage** [comment]
May I try my hand at this?

**Comment by MrRoudyk** [comment]
Can I take this from here?
