### ISSUE TITLE
Move get_quest_users

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#343]
## Description 📹

**Move `src/endpoints/admin/quest_boost/get_quest_users.rs` to `src/endpoints/admin/quest/get_quest_users.rs`.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
   - [ ] Move the file `src/endpoints/admin/quest_boost/get_quest_users.rs` to `src/endpoints/admin/quest/get_quest_users.rs`.
   - [ ] Update all references in the codebase to reflect the new path of `get_quest_users.rs`.
   - [ ] Check the `mod.rs` files (if applicable) and update module imports to ensure the file is correctly included.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Move get_quest_users.rs to the correct directory"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by davedumto** [comment]
Hi I am Dumto, I am a frontend developer, I am a new contributor to the only dust platform and this project. I would love to be assigned this issue. ETA  24 hours

**Comment by Shalomnze** [comment]
I’m interested in this one.

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies.
I would love to contribute to this project.

**Comment by manicdon7** [comment]
Could I be assigned to this?

**Comment by Emmykeyz101** [comment]
Can I jump on this task?

**Comment by CHEF-SAVY** [comment]
I'm a new contributor and I'd like to take this issue.

**Comment by abhirajprasad** [comment]
Can I take care of this issue?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by 3th-Enjay** [comment]
Can I be assigned to this?

**Comment by Nanle100** [comment]
May I try my hand at this?

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by Marchand-Nicolas** [comment]
Done here https://github.com/lfglabs-dev/api.starknet.quest/pull/356
