### ISSUE TITLE
Replace `.expect()` by our own logger in `src/endpoints/quests/carmine/verify_price_protect.rs`

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#344]
## Description 📹

**Replace `.expect()` by our own logger in `src/endpoints/quests/carmine/verify_price_protect.rs`, similar to the implementation in `src/endpoints/quest_boost/get_pending_claims.rs`.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   - [ ] Introduce the logger in the `src/endpoints/quests/carmine/verify_price_protect.rs` handler.
   - [ ] Replace `.expect()` calls with appropriate logging.
   - [ ] Modify the following block:
     ```rust
     if FieldElement::from_hex_be(address.as_str().unwrap()).expect("Failed to parse address")
     ```
     to use the logger for error handling, similar to the approach in `src/endpoints/quest_boost/get_pending_claims.rs`.
   - [ ] Ensure any error handling for `reqwest::get` and JSON parsing uses the logger.
   - Example code snippet:
     ```rust
     let logger = &state.logger;
     match FieldElement::from_hex_be(address.as_str().unwrap()) {
         Ok(parsed_address) => {
             if parsed_address == addr {
                 found = true;
                 break;
             }
         }
         Err(e) => {
             logger.error(format!("Failed to parse address: {}", e));
         }
     }
     ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Replace .expect() with logger in verify_price_protect handler"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by NiteeshPutla** [comment]
I’m interested in this one.

**Comment by AceVikings** [comment]
I’d like to work on this.

**Comment by jsanchez556** [comment]
Hi, I am José Mario, and I am a Senior Full-Stack Developer from Costa Rica, starting to love the development of Web3. I love contributing to open-source projects. Currently learning Rust, Cairo, and dApp development. In the last few months, I have had the opportunity to work with projects involving Rust, Cairo, TypeScript, Git, and Docker, further developing my skill set.
My journey in the tech industry has been fueled by a love for learning and innovation. Since version 7.0, I’ve actively participated in ODHacks, driven by my work with Dojo Coding, which has sharpened my ability to tackle complex challenges collaboratively.
I’m excited to leverage my extensive experience while embracing emerging technologies, pushing boundaries, and delivering impactful solutions in the ever-evolving tech landscape.

Steps to Address the Solution:

1. Identify .expect() calls in src/endpoints/quests/carmine/verify_price_protect.rs and replace them with match statements for error handling.
2. Use the logger to record errors instead of expect(),  similar as in src/endpoints/quest_boost/get_pending_claims.rs
3. Run tests to verify nothing is broken.

**Comment by 0xdevcollins** [comment]
Is it okay if I tackle this?

**Comment by Emmykeyz101** [comment]
Can I start working on this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by abhirajprasad** [comment]
I am interested in taking up this issue! :)

**Comment by codebestia** [comment]
I'd like to handle this task.

## How i will tackle this

- I will fork the repo and create a branch based on this issue number with the `fix-` prefix.
- I will follow the README.md guildeline to get the project running locally.
- I will locate all `.expect()` calls in the `src/endpoints/quests/carmine/verify_price_protect.rs` and replace it with the custom logger as implemented in `src/endpoints/quest_boost/get_pending_claims.rs.`
- I will ensure any  error handling for `request::get` and JSON parsing uses the logger.
- I will run tests to make sure no breaking change occurred 
- I will commit using the `Fix:` to highlight the contribution
- I will complete this task before 2 business and i will make a PR available for review

**Comment by 3th-Enjay** [comment]
Can I take this from here?

**Comment by Nanle100** [comment]
I’d like to help with this.

**Comment by Andres49815** [comment]
Hello! My name is Andres! I am a Computer Engineer from Costa Rica! For the last 3 years I have been working on Software projects on the private sector, and I want to take the jump to Open-Source Software!

To takle this issue, I would go to the `verify_protect.rs` file, change the logger to your own logger, and then committing and pushing following the guidelines you stablished.
I would love to start with an issue like this!

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by MrRoudyk** [comment]
Can I start working on this?

**Comment by Andres49815** [comment]
Hello!
The PR is ready for review, but GH is not letting me assign labels to the PR!
