### ISSUE TITLE
Update the `QuestDocument` struct 

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#348]
## Description 📹

**Update the `QuestDocument` struct in `src/models.rs` to include a new optional `banner` field. Ensure that the new field is serialized and deserialized correctly, and update `src/endpoints/get_quest.rs` to return the `banner` object if it exists. The `banner` object should have the following structure:**

```json
{
   "tag": "Optional",
   "title": "Write a thread on xSTRK",
   "description": "Top 10 threads get $50 each.",
   "cta": "Participate",
   "href": "https://forms.gle/dxcDWjETeYCzRHtG7",
   "image": "/karnot/endurBanner.webp"
}
```

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   Update the codebase with the following steps:
   
   - [ ] Modify the `QuestDocument` struct in `src/models.rs` to include the new optional `banner` field:
   
     ```rust
     pub_struct!(Debug, Serialize, Deserialize; QuestDocument {
         id: u32,
         name: String,
         desc: String,
         additional_desc: Option<String>,
         issuer: String,
         category: String,
         rewards_endpoint: String,
         logo: String,
         rewards_img: String,
         rewards_title: String,
         rewards_description: Option<String>,
         rewards_nfts: Vec<NFTItem>,
         img_card: String,
         title_card: String,
         hidden: Option<bool>,
         disabled: bool,
         expiry: Option<i64>,
         expiry_timestamp: Option<String>,
         mandatory_domain: Option<String>,
         expired: Option<bool>,
         experience: i64,
         start_time: i64,
         banner: Option<Banner>
     });
     
     #[derive(Debug, Serialize, Deserialize)]
     pub struct Banner {
         tag: String,
         title: String,
         description: String,
         cta: String,
         href: String,
         image: String
     }
     ```

   - [ ] Update the `src/endpoints/get_quest.rs` file to ensure it properly fetches and returns the new `banner` field in API responses.

   - [ ] If necessary, modify any other related files to ensure compatibility with the new structure.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Add optional banner field to QuestDocument struct"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 2days.

**Comment by wheval** [comment]
Hello @Marchand-Nicolas,

Can I contribute to this one?

ETA is 1 day

**Comment by Michaelkingsdev** [comment]
Let me handle this please. Will make PR in 15hrs.

**Comment by Emmanex01** [comment]
I'd love to give this a go.

**Comment by KeneePatel** [comment]
Hello Nico,

I am a returning contributor to OnlyDust. I have previously completed several issues on a wide range of projects. The notable ones being kakarot and starknet.js. I will review and follow the community and contributing guidelines making sure the requirements are met properly.

ETA: 1d
Telegram: @patelkenee

**Comment by Supa-mega** [comment]
Hi, May I take care of this?

**Comment by Jagadeeshftw** [comment]
Can I attempt this issue?

**Comment by PedroCo3lho** [comment]
Would love to tackle this!

**Comment by Agbeleshe** [comment]
Could I take over this issue? I will approach this issue by ensuring the data pipeline and UI are synchronized with the updated backend. First, after the backend team implements the new `banner` field in the `QuestDocument` struct and updates the API endpoint, I will fetch the updated API schema and test its response to ensure the banner field is properly serialized. Next, I will update the front-end data models or TypeScript types to include the optional `banner` field. I will then adapt the UI components to conditionally render the `banner` if it exists, ensuring a fallback display for cases where the field is null. Finally, I will write or update tests to verify both the API integration and UI behavior, ensuring the banner displays correctly without breaking the existing functionality. The changes will be committed, pushed to a feature branch, and reviewed before merging.

**Comment by GideonBature** [comment]
Let me try this one!

My name is Gideon Bature, a Software Engineer with experience working with Rust and some of it's framework like Axum, Actix-web etc. I will love to complete this task, and if assigned will send my first PR within 48 hrs.

Thank you!

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Nityam573** [comment]
Can I tackle this one?

**Comment by psychemist** [comment]
Hello, StarQuest project maintainers! 
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience building backend systems, implementing user authentication, and serving web resources over a fully fleshed-out and documented API. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

Over my years of experience, I have worked with tools like:

Web3: Solidity and Rust
Backend: Express.js, Nest.js, Django, FastAPI, and Flask
Frontend: HTML/CSS, JavaScript/TypeScript, , React.js, Next.js, TailwindCSS, and shadcn/ui

Here is how I would solve this task:

- Update the QuestDocument struct in src/models.rs by adding an optional banner field using Rust's Optiontype and defining the banner struct.
- Next, I will modify the src/endpoints/get_quest.rs file by updating the endpoint to fetch and return the banner object in the API response if it exists.
- Afterward, I shall write tests to check for proper serialization and deserialization of the banner field, covering cases where it is present and absent.
- Then, I will review and adjust any related code to support the updated QuestDocument structure and adhere to the codebase conventions.

I aim to complete this task within 48 hours being assigned and setting up my development environment, with my first pull request submitted before 24 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by psychemist** [comment]
Hello, StarknetQuest project maintainers! 
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive experience building backend systems, implementing user authentication, and serving web resources over a fully fleshed-out and documented API. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

Over my years of experience, I have worked with tools like:

Web3: Solidity and Rust
Backend: Express.js, Nest.js, Django, FastAPI, and Flask
Frontend: HTML/CSS, JavaScript/TypeScript, , React.js, Next.js, TailwindCSS, and shadcn/ui

Here is how I would solve this task:

- Update the QuestDocument struct in src/models.rs by adding an optional banner field using Rust's Optiontype and defining the banner struct.
- Next, I will modify the src/endpoints/get_quest.rs file by updating the endpoint to fetch and return the banner object in the API response if it exists.
- Afterward, I shall write tests to check for proper serialization and deserialization of the banner field, covering cases where it is present and absent.
- Then, I will review and adjust any related code to support the updated QuestDocument structure and adhere to the codebase conventions.

I aim to complete this task within 48 hours being assigned and setting up my development environment, with my first pull request submitted before 24 hours have elapsed. I have an incredible work ethic and can deliver on this task.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀

**Comment by helios492** [comment]
Hello! @Marchand-Nicolas
As an experienced fullstack and blockchain developer, I am sure that I can satisfy you with this issue.
I have strong background in problem solving skills.
I can handle this project within 3 business day and you will get what you want.
Thank you for considering my opportunity and will look forward to your contact.
Best Regards.

**Comment by omsant02** [comment]
I would like to work on this issue

1-In models.rs, I'll add a new Banner struct and include it as an optional field in QuestDocument:
-Create the Banner struct with all required fields (tag, title, description, etc.)
-Update QuestDocument to include banner: Option<Banner>
-Add the same field to QuestInsertDocument for consistency

2-In get_quest.rs, since the MongoDB pipeline is already set up correctly to fetch quest documents, the banner field will automatically be included in the response once we add it to the model.

ETA : 1 day

**Comment by 1nonlypiece** [comment]
I'd like to handle this task.

**Comment by Crosstons** [comment]
I'd love to give this a go.

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Cairo.

I will like to take care of this. Will follow the above requirements and create a good PR within 24hours.

**Comment by aurlic** [comment]
I’m interested in this one.
