### ISSUE TITLE
Update mongo setup in the README

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/quest_server#351]
## Description 📹

**Fix the README file to update instructions regarding database setup. Remove references to `db-docker-compose.yml` and provide guidance on obtaining a free MongoDB database from Mongo's website as the preferred setup method.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
   Update the README file to:
   - [ ] Remove instructions for using `db-docker-compose.yml`.
   - [ ] Add clear steps for setting up a free MongoDB database using MongoDB Atlas.
   - [ ] Update `connection_string` instructions to reflect the new setup method.
   - [ ] Adjust troubleshooting steps to align with the new database setup.
   - [ ] Verify consistency in other sections of the README referencing the database setup.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Update README to reflect new MongoDB setup instructions"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Michaelkingsdev** [comment]
Hello @Marchand-Nicolas 
Can i be assigned to this please?

**Comment by Benjtalkshow** [comment]
i can do this

**Comment by ryzen-xp** [comment]
Could I take on this issue?
Hi  , 
I am full stack web3  developer  , I have make many readme.nd  files  for  many project  can you assign this issue to me 
Thank you

**Comment by tasneemtoolba** [comment]
@Marchand-Nicolas 
I can do this

**Comment by michojekunle** [comment]
Hi, I’d like to work on this issue to update the README file with the new database setup instructions. 

My approach:

1. Remove outdated references to db-docker-compose.yml.


2. Add step-by-step instructions for setting up a free MongoDB database using MongoDB Atlas.


3. Update connection_string examples to match the MongoDB Atlas configuration.


4. Adjust troubleshooting tips to align with the new setup.


5. Verify consistency in other README sections referencing the database setup.



I have experience in technical documentation and database integration, ensuring clear and user-friendly instructions.

### ETA 24 hours 

Looking forward to your approval!

**Comment by jaykayudo** [comment]
Can i handle this? @Marchand-Nicolas

**Comment by emarc99** [comment]
I have dev experience doing backend with postgresql, mongodb and mysql. Also devops skills with docker, AWS, Azure.
I will properly test the new connection_string is working, fix any bugs and update the README accordingly.
ETA - 2 days.

**Comment by GideonBature** [comment]
@Marchand-Nicolas can assign this task to me?

My name is Gideon Bature, a Software Engineer. I will provide a detailed and step by step method of getting a mongodb database from mongodb atlas, setting it up and finally make sure the implementation works perfectly without breaking the current functionality. I will complete this task within 48 hrs if assigned.

Thank you!

**Comment by Birdmannn** [comment]
Can I take care of this issue?

**Comment by Birdmannn** [comment]
Please can I handler this. I'm Pascal, a full stack web developer (backend major) in java and Springbok. And I'm proficient in setting up databases like MongoDB and SQL. I shalll write down all steps listed in the description above

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by jaiminRaiyani** [comment]
I’d like to help with this.

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. 

I have successfully done tasks assigned to me in OnlyDust. To solve this task, I will provide a step by step guide that a 10 year old would understand on getting a mongodb database from mongodb atlas docs. I would follow all the instruction given.If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by 0xdevcollins** [comment]
Is it okay if I tackle this?

**Comment by 1nonlypiece** [comment]
Can I handle this task?

**Comment by Amarjeet325** [comment]
Can I tackle this one?

**Comment by Emmanex01** [comment]
Is this issue still available?
I'm Emmanuel, a software developer.
Once assigned this issue, I will deliver as soon as possible. Thanks

**Comment by mimisavage** [comment]
Can I be assigned on this task ?

**Comment by RomThpt** [comment]
Can I tackle this one?
